apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: jassycassy/quotes-back:v1
        name: api
        env:
          - name: SQLALCHEMY_DATABASE_URI
            valueFrom:
              secretKeyRef:
                name: back-secret
                key: password
          - name: SQLALCHEMY_DATABASE_URI
            valueFrom:
              secretKeyRef:
                name: back-secret
                key: username
        ports:
        - containerPort: 3000
          name: http
      restartPolicy: Always


---


apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api      
  ports:
  - name: http
    port: 3000
    targetPort: 3000
